class DataTableList {
  static var viewInvoiceList = [
    {
      'Vendor': 'Comcast',
      'Invoice': 'View Invoice 1',
      'Date': '7-08-2022',
    },
    {
      'Vendor': 'Comcast',
      'Invoice': 'View Invoice 1',
      'Date': '7-08-2022',
    },
    {
      'Vendor': 'Comcast',
      'Invoice': 'View Invoice 1',
      'Date': '7-08-2022',
    },
    {
      'Vendor': 'Comcast',
      'Invoice': 'View Invoice 1',
      'Date': '7-08-2022',
    },
    {
      'Vendor': 'Comcast',
      'Invoice': 'View Invoice 1',
      'Date': '7-08-2022',
    },
    {
      'Vendor': 'Comcast',
      'Invoice': 'View Invoice 1',
      'Date': '7-08-2022',
    },
    {
      'Vendor': 'Comcast',
      'Invoice': 'View Invoice 1',
      'Date': '7-08-2022',
    },
    {
      'Vendor': 'Comcast',
      'Invoice': 'View Invoice 1',
      'Date': '7-08-2022',
    },
    {
      'Vendor': 'Comcast',
      'Invoice': 'View Invoice 1',
      'Date': '7-08-2022',
    },
    {
      'Vendor': 'Comcast',
      'Invoice': 'View Invoice 1',
      'Date': '7-08-2022',
    },
  ];
  static var list = [
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
    {
      'Business': 'Smoking Joes',
      'Corporation': 'Jiya INC',
      'Date': 'July',
      'Business': '\$453565',
      'Tax': '\$3275372',
      'Gas': '\$0',
      'Gallons': '0',
    },
  ];
}
